config:
  client_name: 'Northeastern University'
  default_page: '404'
  days: 5
screens:
    - snell_quad:
        name: 'Snell Library Outdoor Quad'  
        image_url: 'https://www.northeastern.edu/snell_quad.png'
        description:
        quantity: 1
        default_source: banner
    - cabot_quad:
        name: 'Cabot Recreation Center Outdoor Quad'
        image_url: 'www.google.com'
        description:
        quantity: 1
        default_source: banner
    - cabot_indoor_1:
        name: 'Cabot Field House (Type 1)'
        image_url: 'www.google.com'
        quantity: 2
        default_source: banner
    - cabot_indoor_2:
        name: 'Cabot Field House (Type 2)'
        image_url: 'www.google.com'
        quantity: 2
        default_source: banner
    - richards_235:
        name: 'Richards Hall Room 235'
        image_url: 'www.google.com'
        quantity: 1
        default_source: livestream 
sources:
    - livestream:
        name: 'College Ceremonies Livestream'
        path_name: 'livestream'
    - photo_mosaic:
        name: 'Interactive Photo Wall'
        path_name: 'photo_wall'
    - message_board:
        name: 'Interactive Message Board'
        path_name: 'message_board'
    - banner:
        name: 'Commencement Week Banner'
        path_name: 'banner'
schedule:
    - snell_quad:
        - livestream:
            days: '1,4'
            time: '09:15'
        - 
